# Generated by Django 3.1 on 2020-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistudents',
            name='class_num',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
